# Generated by Django 3.2 on 2023-01-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('salary_status', models.PositiveSmallIntegerField(choices=[(1, 'In Flow'), (2, 'Blocked'), (3, 'Disconnection')], verbose_name='salary_status')),
                ('salary_amount', models.IntegerField(verbose_name='salary_amount')),
                ('personal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financials',
                'verbose_name_plural': 'Financials',
                'db_table': 'financial',
            },
        ),
    ]
