# Generated by Django 3.2 on 2023-01-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('uuid', models.AutoField(default=1000000000, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150, verbose_name='subject')),
                ('context', models.TextField(verbose_name='message')),
                ('priority', models.SmallIntegerField(choices=[(1, 'اضطراری'), (2, 'خیلی مهم'), (3, 'مهم'), (4, 'عادی')], default=4, verbose_name='priority')),
                ('attachments', models.FileField(null=True, upload_to='./Ticket_Attachments', verbose_name='attachments')),
                ('status', models.SmallIntegerField(choices=[(0, 'بدون وضعیت'), (1, 'بسته'), (2, 'باز'), (3, 'دریاف شده'), (4, 'پیشنویس')], default=0, verbose_name='status')),
                ('is_read_by_recipient', models.BooleanField(default=False, verbose_name='is_read')),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_depart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
            },
        ),
    ]
