# Generated by Django 3.2 on 2023-01-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('department', models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'Financial'), (3, 'Preservation'), (4, 'Tecnical'), (5, 'Procurement'), (6, 'Transport'), (7, 'Public Relation'), (8, 'Sevice')], primary_key=True, serialize=False, verbose_name='department_id')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
            },
        ),
    ]
